#!/bin/bash

# Handle help seperately, as it appears on stdout with exit code 0
# If any option matches ".*-h.*" then treat as asking for help
for var in "$@"; do
    if [[ "$var" == *"-h"* ]]; then
        echo "$(./otw.py $@)"
        exit 0
    fi
done

# Otherwise, run python script
# If program succeeds, execute output
CONNECTION_COMMAND="$(./otw.py $@)"
if [ $? -eq 0 ]; then
    $CONNECTION_COMMAND
fi

