#!/bin/bash

PYTHON_SCRIPT="OverTheWire/__init__.py"

# Handle help seperately, as it appears on stdout with exit code 0
# If any option matches ".*-h.*" then treat as asking for help
for var in "$@"; do
    if [[ "$var" == *"-h"* ]]; then
        echo "$($PYTHON_SCRIPT $@)"
        exit 0
    fi
done

# Otherwise, run python script
# If program succeeds, execute output
CONNECTION_COMMAND="$($PYTHON_SCRIPT $@)"
if [ $? -eq 0 ]; then
    $CONNECTION_COMMAND
fi

